### ISSUE TITLE
Different home styles

### ISSUE THREAD

**Issue by JuanchiRios** [mumuki/mumuki-platform#220] opened 2017-01-14 22:28 UTC
Sometimes when i entered mumuki it seems like it has brokeen the stylesheet and it shows this page

![captura de pantalla de 2017-01-14 16-47-42](https://cloud.githubusercontent.com/assets/11356439/21958325/94246682-dab4-11e6-87e2-b728e6799aa1.png)

with this [css](http://mumuki.io/assets/application-58c6e102f16425cbce3c5bc58568af699969c51d617e6e158de319abcaa1f7b2.css) but other times appears to be fine like this one

![captura de pantalla de 2017-01-14 19-11-25](https://cloud.githubusercontent.com/assets/11356439/21958449/4824e074-dab7-11e6-94e2-c7f4797c1e1e.png)

With this [css](http://mumuki.io/assets/application-1377509172303684bfcb2eb040566a977b30b9bb71e3c91690dde4f10fe21464.css). The second one when I inspect mumuki's logo, I found out that it has this style for example
```
.book-header img {
    height: 75px;
}
```

Is it possible that you guys are delivering different versions of css?

**Comment by flbulgarelli** [comment] 2017-01-24 04:46
This is a duplicate of https://github.com/mumuki/mumuki-platform/issues/222, which has been fixed a few days ago.

**Closed as completed by flbulgarelli** 2017-01-24 04:46 UTC
