### ISSUE TITLE
Error should be in monotype font

### ISSUE THREAD

**Issue by fdodino** [mumuki/mumuki-platform#128] opened 2016-08-01 10:52 UTC
Eg: http://pdep-utn.mumuki.io/exercises/2642-programacion-con-objetos-objetos-y-mensajes-mensajes-segunda-parte

If you type pepita.bailar()
![image](https://cloud.githubusercontent.com/assets/4549002/17291887/d57b88f2-57bc-11e6-8c50-d463c135f407.png)
Error is displayed in a non monotype font.

**Comment by flbulgarelli** [comment] 2016-08-09 06:03
Duplicate of https://github.com/mumuki/mumuki-atheneum/issues/292

**Closed as completed by flbulgarelli** 2016-08-09 06:03 UTC
