### ISSUE TITLE
Status on submission

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-platform#298] opened 2015-09-09 02:28 UTC
Add status on submission api

**Comment by flbulgarelli** [comment] 2015-09-10 20:08
It seems to be fixed in masters. I think I did the dump with an old version of the platform. Let me check

**Comment by flbulgarelli** [comment] 2015-09-10 21:22
Confirmed, on master is currently being notified as expected:

```json
{
	"id" : 43787,
	"content" : "personaje(arya,stark(14,mujer)).\r\npersonaje(cersei,stark(34,mujer)).",
	"created_at" : "2015-07-29T15:33:21.590Z",
	"updated_at" : "2015-09-07T20:02:17.038Z",
	"status" : "failed",
	"result" : "```\n...\nERROR: /tmp/mumuki.compile20150729-3-1y41xf:11:\n\ttest cersei_es_mujer: failed\n\nERROR: /tmp/mumuki.compile20150729-3-1y41xf:14:\n\ttest cersei_tiene_34: failed\n\nERROR: /tmp/mumuki.compile20150729-3-1y41xf:17:\n\ttest cersei_es_lannister: failed\n\n\n```",
	"submitter_id" : ...,
	"expectation_results" : [ ],
	"feedback" : "* Tu código no pasó nuestras pruebas. Revisá si hiciste lo que pide el enunciado, y si **respetaste el orden de los parámetros** en los predicados solicitados",
	"test_results" : [ ],
	"exercise" : {
		"id" : 312,
		"guide_id" : 30
	},
	"submitter" : {
		"id" : ...,
		"name" : ...
	}
}


```

**Closed by flbulgarelli** 2015-09-10 21:22 UTC
