### ISSUE TITLE
Removing an exercise in the editor doesn't remove it in Atheneum

### ISSUE THREAD

**Issue by matifreyre** [mumuki/mumuki-platform#68] opened 2016-04-26 23:02 UTC
After removing an exercise in the editor, Atheneum looks like this:
![image](https://cloud.githubusercontent.com/assets/10454118/14836856/a7ffa2e2-0be9-11e6-940d-d60d6b71a009.png)

You can see 3 exercises with the number 6: The current one and 2 previously deleted.

Example: http://mumuki.io/guides/215-tp-fun-2-sabados-manana-series-de-t2

**Comment by flbulgarelli** [comment] 2016-04-27 02:51
Hi, this is a duplicate of #44

**Closed as completed** 2016-05-08 07:03 UTC
